# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# ActiveMQ Artemis

FROM centos:6 as builder-env

LABEL maintainer="Apache ActiveMQ Team"

RUN yum groupinstall -y "Development Tools" && \
	yum install -y vim cmake libaio libaio.i686 libaio-devel libaio-devel.i686 glibc-devel.i686 \
		libgcc.i686 java-1.8.0-openjdk-devel && yum clean all

FROM builder-env as builder

ADD . /work

WORKDIR /work

VOLUME ["/work/target/lib"]
VOLUME ["/root/.m2/repository"]

WORKDIR /work

CMD [ "sh", "-c", "/work/scripts/compile-native.sh"]
