# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# ActiveMQ Artemis

FROM openjdk:8
LABEL maintainer="Apache ActiveMQ Team"

USER root

RUN apt-get update

#RUN apt-get install -y gcc-6-multilib
#RUN apt-get install -y glibc-devel.i686 libaio-devel.i686
#RUN apt-get install -qq -y libaio-devel

RUN apt-get install -qq -y bash

#vim is useful for eventual debugging inside the image
RUN apt-get install -qq -y cmake make vim
RUN apt-get install -qq -y g++
RUN apt-get install -qq -y libaio1
RUN apt-get install -qq -y libaio-dev
RUN groupadd -g 1001 -r artemis && useradd -r -u 1001 -g artemis artemis

ADD . /work

# Expose some outstanding folders
VOLUME ["/work/target/lib"]
WORKDIR /work

CMD ["RUN"]
